version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: money_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "20406:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:   # phpMyAdmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "10407:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 1234
      PMA_ARBITRARY: 1
    depends_on:
      mysql:
        condition: service_started

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 261146
      POSTGRES_DB: Money
    ports:
      - "25432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "10408:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      postgres:
        condition: service_started

  web:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      #- "10406:5173" อันนี้ที่เราสร้างขึ้นมาเอง
      - "10.80.24.11:10406:5173" # IP เครื่อง
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      mysql:
        condition: service_started
      postgres:
        condition: service_started

  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
     # - "80:80"  อันนี้งานแรก
      - "10.80.24.11:80:80"  # bind nginx เฉพาะ IP อันนี้คือ ipเครื่องมอ
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      web:
        condition: service_started
volumes:
  mysql_data:
  postgres_data:
